CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER NOT NULL,
    DATA_LIMIT NUMBER NOT NULL,
    MINUTE_LIMIT NUMBER NOT NULL,
    SMS_LIMIT NUMBER NOT NULL
);

CREATE INDEX idx_tariffs_name ON TARIFFS(NAME);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    SIGNUP_DATE DATE NOT NULL,
    TARIFF_ID NUMBER NOT NULL,
    CONSTRAINT fk_customers_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE INDEX idx_customers_city ON CUSTOMERS(CITY);
CREATE INDEX idx_customers_tariff ON CUSTOMERS(TARIFF_ID);
CREATE INDEX idx_customers_signup ON CUSTOMERS(SIGNUP_DATE);

CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    DATA_USAGE NUMBER(10, 2) NOT NULL,
    MINUTE_USAGE NUMBER NOT NULL,
    SMS_USAGE NUMBER NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_stats_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX idx_monthly_stats_customer ON MONTHLY_STATS(CUSTOMER_ID);
CREATE INDEX idx_monthly_stats_payment ON MONTHLY_STATS(PAYMENT_STATUS);
